repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
  
  - repo: local
    hooks:
      - id: mypy
        name: Check mypy
        entry: mypy --namespace-packages -p camel_scale -p test
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
